# Generated by Django 2.1.7 on 2019-02-27 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('time_from_week', models.PositiveSmallIntegerField(null=True, verbose_name='godzina otwarcia w tygodniu')),
                ('time_to_week', models.PositiveSmallIntegerField(null=True, verbose_name='godzina zamknięcia w tygodniu')),
                ('time_from_weekend', models.CharField(max_length=64, verbose_name='godzina otwarcia w weekend')),
                ('time_to_weekend', models.CharField(max_length=64, null=True, verbose_name='godzina zamknięcia weekend')),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='tailor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Tailor'),
        ),
    ]
