# Generated by Django 2.1.5 on 2019-01-23 12:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='time_from_week',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='godzina otwarcia w tygodniu'),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='time_from_weekend',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='godzina otwarcia w weekend'),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='time_to_week',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='godzina zamknięcia w tygodniu'),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='time_to_weekend',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='godzina zamknięcia weekend'),
        ),
    ]
