# Generated by Django 2.1.5 on 2019-01-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190123_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
