# Generated by Django 2.1.5 on 2019-01-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190123_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='time_from_weekend',
            field=models.PositiveSmallIntegerField(null='nieczynne', verbose_name='godzina otwarcia w weekend'),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='time_to_weekend',
            field=models.PositiveSmallIntegerField(null='nieczynne', verbose_name='godzina zamknięcia weekend'),
        ),
    ]
