# Generated by Django 2.1.5 on 2019-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190123_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='time_from_weekend',
            field=models.CharField(default=10, max_length=64, verbose_name='godzina otwarcia w weekend'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tailor',
            name='time_to_weekend',
            field=models.CharField(default=18, max_length=64, verbose_name='godzina zamknięcia weekend'),
            preserve_default=False,
        ),
    ]
