# Generated by Django 2.1.5 on 2019-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190123_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='time_to_weekend',
            field=models.CharField(max_length=64, null=True, verbose_name='godzina zamknięcia weekend'),
        ),
    ]
